spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    username: admin
    password: 1q2w3e4r
    url: jdbc:mysql://portfolio.cobrokkm0djp.ap-northeast-2.rds.amazonaws.com:3306/travel
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 578802875185-jgifttkes4j865ma41p6b23tfhv1fqql.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://ec2-43-202-21-26.ap-northeast-2.compute.amazonaws.com/login/oauth2/code/google
            scope:
              - profile
              - email
          kakao:
            client-id: e3036e772985f223908789d51a382977
            client-secret: yaBs2Q2zC86dBwYsolYqDBqMCAQv4gCm
            redirect-uri: http://ec2-43-202-21-26.ap-northeast-2.compute.amazonaws.com/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
          naver:
            client-id: qz7c3rpgyf_pcchPO8_j
            client-secret: 0xKVlIOyGA
            redirect-uri: http://ec2-43-202-21-26.ap-northeast-2.compute.amazonaws.com/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

mybatis:
  mapper-locations:
    - /mappers/*.xml

jwt:
  secret: 5jvk3bQ0WwrChdr9u1aJajI8vydU4RG5auz9VOsEekT1zvljnfIigblVXXypuU82

file:
  path: /app/upload/
#  path: C:/aws_project/workspace/KORIT-LSLC-portfolio-app/upload/